steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/jones:latest
  - --cache=true
  - --cache-ttl=10h
  - --timeout=2400s
  id: docker build build using kaniko cache
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/jones:latest' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy',
          'jones',
          '--image', 'gcr.io/$PROJECT_ID/jones:latest']
  id: service deploy to cloud run
