steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/jones:latest', '--timeout=2400s' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/jones:latest' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy',
          'jones',
          '--image', 'gcr.io/$PROJECT_ID/jones:latest']
  id: service deploy to cloud run
